# Generated by Django 2.1.5 on 2019-01-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='playlist',
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
