# Generated by Django 2.1.5 on 2019-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
