# Generated by Django 2.1.5 on 2019-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190110_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='lng',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True),
        ),
    ]
