# Generated by Django 2.1.5 on 2019-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190111_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='place_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
