# Generated by Django 2.1.5 on 2019-01-17 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190114_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('playlist', 'user')},
        ),
    ]
