# Generated by Django 2.1.5 on 2019-01-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_votes', to='core.Playlist'),
        ),
    ]
